### ISSUE TITLE
Expert Data is missing?

### ISSUE THREAD

**Issue by guyuwuyu** [ArashVahabpour/sog-gail#1]
Dear Arash:
              the webpage of expert data in README.MD is missing，and i downloaded the data in the /gail_expert, finding the data seems not to be expert, like trajs_ant.h5, there is no explict 6 direction in the plot below.could you please release the expert dataset again? thanks!

![image](https://user-images.githubusercontent.com/56181038/185893566-e4e88a54-f413-4e53-b30a-24508cacc863.png)

**Comment by ArashVahabpour** [comment]
sure, I will do that soon.

**Comment by guyuwuyu** [comment]
> Thanks so much for your interest. Sure, I will do that by the end of the week.

Thanks again and best wishes!

**Comment by ArashVahabpour** [comment]
I corrected the link. The files are going to be uploaded in the next few hours :)

**Comment by guyuwuyu** [comment]
> 

love you ~~
